apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistenceVolume.name }}
spec:
  capacity:
    storage: {{ .Values.persistenceVolume.size }}
  accessModes:
    {{- range .Values.persistenceVolume.accessModes }}
    - {{ . }}
    {{- end }}
  persistentVolumeReclaimPolicy: {{ .Values.persistenceVolume.reclaimPolicy }}
  nfs:
    server: {{ .Values.persistenceVolume.nfsServer }}
    path: {{ .Values.persistenceVolume.nfsPath }}
  mountOptions:
    {{- range .Values.persistenceVolume.mountOptions }}
    - {{ . }}
    {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistenceVolumeClaim.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    {{- range .Values.persistenceVolumeClaim.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistenceVolumeClaim.size }}
  volumeName: {{ .Values.persistenceVolume.name }}